export const REDUCER_KEY = "civil/blockchain";

export enum actionTypes {
  SET_IS_NEWSROOM_EDITOR = "CIVIL:SET_IS_NEWSROOM_EDITOR",
  SET_CURRENT_USER_ID = "CIVIL:SET_CURRENT_USER_ID",
  SET_USERNAME = "CIVIL:SET_USERNAME",
  SET_LOGGED_IN_USER_ADDRESS = "CIVIL:SET_LOGGED_IN_USER_ADDRESS",
  SET_USER_CAPABILITIES = "CIVIL:SET_USER_CAPABILITIES",
  UPDATE_SIGNATURES = "CIVIL:UPDATE_SIGNATURES",
  UPDATE_PUBLISHED_STATE = "CIVIL:UPDATE_PUBLISHED_STATE",
  ADD_OR_UPDATE_REVISION = "CIVIL:ADD_OR_UPDATE_REVISION",
  SET_CIVIL_CONTENT_ID = "CIVIL:SET_CIVIL_CONTENT_ID",
  CHANGE_NETWORK = "CIVIL:CHANGE_NETWORK",
  SET_TX_HASH = "SET_TX_HASH",
}
